// Diagnostic iPhone build only. This records stable fingerprints and counts,
// never cookie/storage keys or values. Work is event-driven and bounded to
// document lifecycle boundaries plus the first trusted touch after each show.
export const SHEIN_PERSISTENT_STATE_DIAGNOSTIC_SCRIPT = `!function(){
  if(window.top!==window||window.__otlobliPersistentStateDiagnostic)return;
  var seq=0,touchArmed=1;
  function hash(v){v=String(v==null?'':v);var h=2166136261;for(var i=0;i<v.length;i++)h=Math.imul(h^v.charCodeAt(i),16777619);return('00000000'+(h>>>0).toString(16)).slice(-8)}
  function storage(s){try{var keys=[],rows=[];for(var i=0;i<s.length;i++)keys.push(String(s.key(i)||''));keys.sort();for(var j=0;j<keys.length;j++)rows.push(hash(keys[j])+':'+hash(s.getItem(keys[j])||''));return{count:keys.length,keysHash:hash(keys.map(hash).join('|')),stateHash:hash(rows.join('|'))}}catch(e){return{count:-1,keysHash:'error',stateHash:'error'}}}
  function cookies(){try{var rows=String(document.cookie||'').split(';').map(function(x){return x.trim()}).filter(Boolean).map(function(x){var p=x.indexOf('='),k=p<0?x:x.slice(0,p),v=p<0?'':x.slice(p+1);return[hash(k),hash(v)]}).sort(function(a,b){return a[0]<b[0]?-1:a[0]>b[0]?1:0});return{count:rows.length,keysHash:hash(rows.map(function(x){return x[0]}).join('|')),stateHash:hash(rows.map(function(x){return x.join(':')}).join('|'))}}catch(e){return{count:-1,keysHash:'error',stateHash:'error'}}}
  function route(){var p=String(location.pathname||'');return /\\/risk\\/|challenge|captcha/i.test(p)?'challenge':/-p-\\d+/i.test(p)?'product':/^\\/(?:[a-z]{2}(?:-[A-Z]{2})?)?\\/?$/i.test(p)?'home':/search|category|collection|campaign|daily|recommend/i.test(p)?'list':'other'}
  function send(stage,data){try{var d=data||{};d.type='otlobliPersistentStateDiagnostic';d.stage=stage;d.seq=++seq;d.at=Date.now();d.route=route();d.routeHash=hash(location.host+location.pathname);var h=window.webkit&&window.webkit.messageHandlers&&window.webkit.messageHandlers.messageHandler;if(h)h.postMessage({detail:d});else if(window.mobileApp&&window.mobileApp.postMessage)window.mobileApp.postMessage({detail:d})}catch(e){}}
  function sync(stage){var c=cookies(),l=storage(localStorage),s=storage(sessionStorage);send('sync:'+stage,{cookieCount:c.count,cookieKeysHash:c.keysHash,cookieStateHash:c.stateHash,localCount:l.count,localKeysHash:l.keysHash,localStateHash:l.stateHash,sessionCount:s.count,sessionKeysHash:s.keysHash,sessionStateHash:s.stateHash,ready:document.readyState,visibility:document.visibilityState})}
  function asyncState(stage){var jobs=[];jobs.push(typeof caches!=='undefined'&&caches.keys?caches.keys().then(function(x){x=x.map(String).sort();return{cacheCount:x.length,cacheHash:hash(x.map(hash).join('|'))}}).catch(function(){return{cacheCount:-1,cacheHash:'error'}}):Promise.resolve({cacheCount:-2,cacheHash:'unsupported'}));jobs.push(navigator.serviceWorker&&navigator.serviceWorker.getRegistrations?navigator.serviceWorker.getRegistrations().then(function(x){var a=x.map(function(r){return hash(r.scope||'')}).sort();return{workerCount:x.length,workerHash:hash(a.join('|')),workerControlled:!!navigator.serviceWorker.controller}}).catch(function(){return{workerCount:-1,workerHash:'error',workerControlled:!!navigator.serviceWorker.controller}}):Promise.resolve({workerCount:-2,workerHash:'unsupported',workerControlled:false}));jobs.push(typeof indexedDB!=='undefined'&&indexedDB.databases?indexedDB.databases().then(function(x){var a=x.map(function(d){return hash(d.name||'')+':'+String(d.version||0)}).sort();return{databaseCount:x.length,databaseHash:hash(a.join('|'))}}).catch(function(){return{databaseCount:-1,databaseHash:'error'}}):Promise.resolve({databaseCount:-2,databaseHash:'unsupported'}));Promise.all(jobs).then(function(x){var d={};for(var i=0;i<x.length;i++)for(var k in x[i])d[k]=x[i][k];send('async:'+stage,d)})}
  function snapshot(stage){sync(stage);asyncState(stage)}
  window.__otlobliPersistentStateDiagnostic=function(stage){stage=String(stage||'native');if(stage.indexOf('native-show')===0)touchArmed=1;snapshot(stage)};
  addEventListener('DOMContentLoaded',function(){snapshot('dom-content-loaded')},{once:true,capture:true});
  addEventListener('pageshow',function(e){snapshot(e.persisted?'pageshow-persisted':'pageshow')},true);
  addEventListener('visibilitychange',function(){if(document.visibilityState==='visible')snapshot('visibility-visible')},true);
  addEventListener('touchstart',function(e){if(!touchArmed||!e.isTrusted)return;touchArmed=0;snapshot('first-trusted-touch')},{capture:true,passive:true});
  snapshot('document-start');
}();`
