// Dedicated iPhone diagnostic build only. The probe is event-driven and
// read-only: it does not patch page APIs, scan or mutate the DOM, intercept
// input, prevent events, reload, clear data, or schedule recurring work.
// Query strings and fragments are stripped before URLs cross the native bridge.
export const SHEIN_FREEZE_DIAGNOSTIC_SCRIPT = `!function(){
  'use strict';
  if(window.top!==window||window.__otlobliCleanRuntimeDiagnosticInstalled)return;
  window.__otlobliCleanRuntimeDiagnosticInstalled=true;
  var sequence=0,lastResourceIndex=0,resourceEvidenceRemaining=80;
  var documentId=String(Date.now())+'-'+String(Math.round(performance.now()));
  function text(value,limit){var result='';try{result=String(value==null?'':value)}catch(error){result='[unprintable]'}return result.slice(0,limit)}
  function hash(value){value=text(value,8192);var result=2166136261;for(var index=0;index<value.length;index++)result=Math.imul(result^value.charCodeAt(index),16777619);return('00000000'+(result>>>0).toString(16)).slice(-8)}
  function safeUrl(value){try{var url=new URL(String(value||''),location.href);return text(url.origin+url.pathname,1024)}catch(error){return text(String(value||'').split(/[?#]/)[0],1024)}}
  function cleanStack(value){return text(value,8192).replace(/https?:\\/\\/[^\\s)>\\]}]+/g,function(url){return safeUrl(url)}).slice(0,4096)}
  function bridge(){return window.webkit&&window.webkit.messageHandlers&&window.webkit.messageHandlers.messageHandler}
  function send(stage,extra){try{var detail={type:'otlobliCleanRuntimeDiagnostic',stage:stage,sequence:++sequence,at:Date.now(),performanceNow:Math.round(performance.now()),documentId:documentId,url:safeUrl(location.href),visibility:document.visibilityState,readyState:document.readyState,online:navigator.onLine!==false};if(extra)for(var key in extra)if(Object.prototype.hasOwnProperty.call(extra,key))detail[key]=extra[key];var handler=bridge();if(handler)handler.postMessage({detail:detail});else if(window.mobileApp&&window.mobileApp.postMessage)window.mobileApp.postMessage({detail:detail})}catch(error){}}
  function errorDetail(error){var value=error&&error.error,source=error&&error.filename;return{message:text(error&&error.message,1024),errorName:text(value&&value.name,80),source:safeUrl(source),line:Number(error&&error.lineno||0),column:Number(error&&error.colno||0),stack:cleanStack(value&&(value.stack||value.message)||'')}}
  addEventListener('error',function(event){var target=event&&event.target;if(target&&target!==window&&!(typeof ErrorEvent!=='undefined'&&event instanceof ErrorEvent)){send('resource-error',{tag:text(target.tagName,32),resourceUrl:safeUrl(target.currentSrc||target.src||target.href||''),resourceType:text(target.type,80),resourceRel:text(target.rel,80),resourceAs:text(target.as,80)});return}send('javascript-error',errorDetail(event))},true);
  addEventListener('unhandledrejection',function(event){var reason=event&&event.reason;send('promise-rejection',{message:text(reason&&(reason.message||reason),1024),errorName:text(reason&&reason.name,80),stack:cleanStack(reason&&(reason.stack||reason.message)||'')})},true);
  addEventListener('securitypolicyviolation',function(event){send('csp-violation',{blockedUrl:safeUrl(event&&event.blockedURI),source:safeUrl(event&&event.sourceFile),effectiveDirective:text(event&&event.effectiveDirective,120),violatedDirective:text(event&&event.violatedDirective,120),disposition:text(event&&event.disposition,32),line:Number(event&&event.lineNumber||0),column:Number(event&&event.columnNumber||0),statusCode:Number(event&&event.statusCode||0)})},true);
  function sampledValue(value){value=text(value,1048576);return String(value.length)+':'+value.slice(0,2048)+':'+value.slice(-2048)}
  function storageState(storage){try{var keys=[],rows=[],limit=Math.min(storage.length,160);for(var index=0;index<limit;index++)keys.push(String(storage.key(index)||''));keys.sort();for(var row=0;row<keys.length;row++)rows.push(hash(keys[row])+':'+hash(sampledValue(storage.getItem(keys[row])||'')));return{count:storage.length,sampled:keys.length,keysHash:hash(keys.join('|')),stateHash:hash(rows.join('|'))}}catch(error){return{count:-1,sampled:0,keysHash:'error',stateHash:hash(error&&error.name||'error')}}}
  function cookieState(){try{var rows=String(document.cookie||'').split(';').map(function(row){return row.trim()}).filter(Boolean).map(function(row){var split=row.indexOf('='),key=split<0?row:row.slice(0,split),value=split<0?'':row.slice(split+1);return hash(key)+':'+hash(sampledValue(value))}).sort();return{count:rows.length,stateHash:hash(rows.join('|'))}}catch(error){return{count:-1,stateHash:hash(error&&error.name||'error')}}}
  function syncStorage(stage){var cookies=cookieState(),local=storageState(localStorage),session=storageState(sessionStorage);send('storage-sync',{snapshotStage:stage,cookieCount:cookies.count,cookieStateHash:cookies.stateHash,localCount:local.count,localSampled:local.sampled,localKeysHash:local.keysHash,localStateHash:local.stateHash,sessionCount:session.count,sessionSampled:session.sampled,sessionKeysHash:session.keysHash,sessionStateHash:session.stateHash})}
  function asyncStorage(stage){var jobs=[];jobs.push(typeof caches!=='undefined'&&caches.keys?caches.keys().then(function(names){names=names.map(String).sort();return{cacheCount:names.length,cacheHash:hash(names.join('|'))}}).catch(function(error){return{cacheCount:-1,cacheHash:hash(error&&error.name||'error')}}):Promise.resolve({cacheCount:-2,cacheHash:'unsupported'}));jobs.push(navigator.serviceWorker&&navigator.serviceWorker.getRegistrations?navigator.serviceWorker.getRegistrations().then(function(registrations){var scopes=registrations.map(function(registration){return safeUrl(registration.scope)}).sort();var controller=navigator.serviceWorker.controller;return{workerCount:registrations.length,workerHash:hash(scopes.join('|')),workerControlled:!!controller,workerControllerUrl:safeUrl(controller&&controller.scriptURL||'')}}).catch(function(error){return{workerCount:-1,workerHash:hash(error&&error.name||'error'),workerControlled:!!navigator.serviceWorker.controller,workerControllerUrl:''}}):Promise.resolve({workerCount:-2,workerHash:'unsupported',workerControlled:false,workerControllerUrl:''}));jobs.push(typeof indexedDB!=='undefined'&&indexedDB.databases?indexedDB.databases().then(function(databases){var rows=databases.map(function(database){return hash(database.name||'')+':'+String(database.version||0)}).sort();return{databaseCount:databases.length,databaseHash:hash(rows.join('|'))}}).catch(function(error){return{databaseCount:-1,databaseHash:hash(error&&error.name||'error')}}):Promise.resolve({databaseCount:-2,databaseHash:'unsupported'}));jobs.push(navigator.storage&&navigator.storage.estimate?navigator.storage.estimate().then(function(estimate){return{storageUsage:Number(estimate.usage||0),storageQuota:Number(estimate.quota||0)}}).catch(function(){return{storageUsage:-1,storageQuota:-1}}):Promise.resolve({storageUsage:-2,storageQuota:-2}));Promise.all(jobs).then(function(parts){var detail={snapshotStage:stage};for(var index=0;index<parts.length;index++)for(var key in parts[index])detail[key]=parts[index][key];send('storage-async',detail)})}
  function navigationSnapshot(stage){try{var entries=performance.getEntriesByType('navigation'),entry=entries&&entries[0];if(!entry){send('navigation-timing',{snapshotStage:stage,navigationType:'legacy',redirectCount:Number(performance.navigation&&performance.navigation.redirectCount||0)});return}send('navigation-timing',{snapshotStage:stage,navigationType:text(entry.type,32),redirectCount:Number(entry.redirectCount||0),responseStatus:Number(entry.responseStatus||0),startTime:Math.round(entry.startTime||0),domainLookupStart:Math.round(entry.domainLookupStart||0),connectStart:Math.round(entry.connectStart||0),secureConnectionStart:Math.round(entry.secureConnectionStart||0),requestStart:Math.round(entry.requestStart||0),responseStart:Math.round(entry.responseStart||0),responseEnd:Math.round(entry.responseEnd||0),domInteractive:Math.round(entry.domInteractive||0),domContentLoaded:Math.round(entry.domContentLoadedEventEnd||0),loadEventEnd:Math.round(entry.loadEventEnd||0),transferSize:Number(entry.transferSize||0),encodedBodySize:Number(entry.encodedBodySize||0),decodedBodySize:Number(entry.decodedBodySize||0)})}catch(error){send('navigation-timing-error',{snapshotStage:stage,message:text(error&&error.message,256)})}}
  function resourceSnapshot(stage){try{var entries=performance.getEntriesByType('resource')||[],statusErrors=0,zeroTransfer=0,totalTransfer=0,totalEncoded=0,totalDecoded=0;for(var index=0;index<entries.length;index++){var current=entries[index],status=Number(current.responseStatus||0),transfer=Number(current.transferSize||0);if(status>=400)statusErrors++;if(transfer===0)zeroTransfer++;totalTransfer+=transfer;totalEncoded+=Number(current.encodedBodySize||0);totalDecoded+=Number(current.decodedBodySize||0)}send('resource-summary',{snapshotStage:stage,resourceCount:entries.length,newResourceCount:Math.max(0,entries.length-lastResourceIndex),statusErrorCount:statusErrors,zeroTransferCount:zeroTransfer,totalTransferSize:totalTransfer,totalEncodedBodySize:totalEncoded,totalDecodedBodySize:totalDecoded});for(var row=lastResourceIndex;row<entries.length&&resourceEvidenceRemaining>0;row++){var entry=entries[row],entryStatus=Number(entry.responseStatus||0),initiator=text(entry.initiatorType,40),entryTransfer=Number(entry.transferSize||0),important=entryStatus>=400||entryTransfer===0||initiator==='script'||initiator==='fetch'||initiator==='xmlhttprequest';if(!important)continue;resourceEvidenceRemaining--;send('resource-entry',{snapshotStage:stage,resourceUrl:safeUrl(entry.name),initiatorType:initiator,responseStatus:entryStatus,duration:Math.round(entry.duration||0),startTime:Math.round(entry.startTime||0),transferSize:entryTransfer,encodedBodySize:Number(entry.encodedBodySize||0),decodedBodySize:Number(entry.decodedBodySize||0),protocol:text(entry.nextHopProtocol,40),renderBlockingStatus:text(entry.renderBlockingStatus,40)})}lastResourceIndex=entries.length}catch(error){send('resource-snapshot-error',{snapshotStage:stage,message:text(error&&error.message,256)})}}
  function fullSnapshot(stage){syncStorage(stage);asyncStorage(stage);navigationSnapshot(stage);resourceSnapshot(stage)}
  function lifecycle(stage,extra){send('document-lifecycle',Object.assign({lifecycleStage:stage},extra||{}))}
  lifecycle('document-start');
  syncStorage('document-start');
  asyncStorage('document-start');
  navigationSnapshot('document-start');
  addEventListener('DOMContentLoaded',function(){lifecycle('dom-content-loaded');fullSnapshot('dom-content-loaded')},{once:true,capture:true});
  addEventListener('load',function(){lifecycle('load');fullSnapshot('load')},{once:true,capture:true});
  addEventListener('pageshow',function(event){lifecycle('pageshow',{persisted:!!event.persisted});fullSnapshot(event.persisted?'pageshow-persisted':'pageshow')},true);
  addEventListener('pagehide',function(event){lifecycle('pagehide',{persisted:!!event.persisted});syncStorage('pagehide');navigationSnapshot('pagehide');resourceSnapshot('pagehide')},true);
  addEventListener('visibilitychange',function(){lifecycle('visibilitychange');if(document.visibilityState==='hidden'){syncStorage('visibility-hidden');navigationSnapshot('visibility-hidden');resourceSnapshot('visibility-hidden')}else fullSnapshot('visibility-visible')},true);
  ['freeze','resume','focus','blur','online','offline','popstate','hashchange'].forEach(function(name){addEventListener(name,function(){lifecycle(name)},true)});
}();`
