project_id = "damanak"

[api]
enabled = true
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
shadow_port = 54330
major_version = 17

[studio]
enabled = true
port = 54333

[auth]
enabled = true
site_url = "com.damanak.damanak://login-callback"
additional_redirect_urls = ["com.damanak.damanak://login-callback"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

[functions.legal]
verify_jwt = false

[functions.warranty-card]
verify_jwt = false

[functions.damanak-api]
verify_jwt = false

[functions.dispatch-webhooks]
verify_jwt = false
